-- ==========================================
-- FILM4U AI - FULL DATABASE SCHEMA
-- ==========================================

-- 1. CLEANUP (Optional - Use with caution)
-- DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
-- DROP FUNCTION IF EXISTS public.handle_new_user();
-- DROP TABLE IF EXISTS watch_history;
-- DROP TABLE IF EXISTS user_library;
-- DROP TABLE IF EXISTS movies_indie;
-- DROP TABLE IF EXISTS movies_ott;
-- DROP TABLE IF EXISTS profiles;

-- ==========================================
-- 2. CORE TABLES
-- ==========================================

-- PROFILES: AI-Tuned User Preferences
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  preferred_language TEXT DEFAULT 'English',
  preferred_genres TEXT[] DEFAULT '{}',
  preferred_moods TEXT[] DEFAULT '{}', -- comfort, dark, nostalgic, hype
  sensitivity_toggles JSONB DEFAULT '{"violence": false, "sadness": false}', 
  mood_history JSONB DEFAULT '[]', -- History of mood searches & picks
  last_active TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  avatar_url TEXT
);

-- MOVIES (OTT): Managed Catalog
CREATE TABLE IF NOT EXISTS public.movies_ott (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  poster TEXT,
  banner TEXT,
  platform TEXT,
  release_date DATE,
  tags TEXT[],
  language TEXT,
  moods TEXT[],
  quality TEXT DEFAULT '4K',
  official_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MOVIES (INDIE): User-Generated Content
CREATE TABLE IF NOT EXISTS public.movies_indie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id UUID REFERENCES auth.users ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  poster TEXT,
  banner TEXT,
  stream_url TEXT,
  tags TEXT[],
  language TEXT,
  moods TEXT[],
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- USER LIBRARY: Favorites & Watchlist Unified
CREATE TABLE IF NOT EXISTS public.user_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  movie_id BIGINT NOT NULL,
  movie_type TEXT NOT NULL CHECK (movie_type IN ('ott', 'indie')),
  list_type TEXT NOT NULL CHECK (list_type IN ('favorite', 'watchlist')),
  added_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, movie_id, movie_type, list_type)
);

-- WATCH HISTORY: Deep Behavioral Tracking
CREATE TABLE IF NOT EXISTS public.watch_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  movie_id BIGINT,
  movie_type TEXT, 
  genre TEXT,
  language TEXT,
  mood_at_watch TEXT, -- Mood selected by user before watching
  time_of_day TEXT, -- 'morning', 'afternoon', 'evening', 'night'
  watched_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. STORAGE BUCKETS
-- ==========================================

-- Create buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES ('posters', 'posters', true),
       ('videos', 'videos', true),
       ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id IN ('posters', 'videos', 'avatars') );
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id IN ('posters', 'videos', 'avatars') AND auth.role() = 'authenticated' );
CREATE POLICY "Owner Update" ON storage.objects FOR UPDATE USING ( bucket_id IN ('posters', 'videos', 'avatars') AND auth.uid() = owner );
CREATE POLICY "Owner Delete" ON storage.objects FOR DELETE USING ( bucket_id IN ('posters', 'videos', 'avatars') AND auth.uid() = owner );

-- ==========================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movies_ott ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movies_indie ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watch_history ENABLE ROW LEVEL SECURITY;

-- 4.1 Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- 4.2 Movies (Publicly Readable)
CREATE POLICY "Movies OTT viewable by all." ON movies_ott
  FOR SELECT USING (true);

CREATE POLICY "Movies Indie viewable by all." ON movies_indie
  FOR SELECT USING (true);

-- 4.3 Movies Indie (Creator Management)
CREATE POLICY "Creators can insert indie movies." ON movies_indie
  FOR INSERT WITH CHECK (auth.uid() = creator_id);

CREATE POLICY "Creators can update own indie movies." ON movies_indie
  FOR UPDATE USING (auth.uid() = creator_id);

-- 4.4 User Library (Private Access)
CREATE POLICY "Users can view own library." ON user_library
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert to own library." ON user_library
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete from own library." ON user_library
  FOR DELETE USING (auth.uid() = user_id);

-- 4.5 Watch History (Private & Append-only)
CREATE POLICY "Users can see their own history." ON watch_history
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert history." ON watch_history
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- 5. AUTOMATION (TRIGGERS)
-- ==========================================

-- Automate profile creation on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 6. ABUSE PROTECTION & QUOTAS
-- ==========================================

-- USER QUOTAS: Daily Limits & Request Tracking
CREATE TABLE IF NOT EXISTS public.user_quotas (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  daily_ai_requests INTEGER DEFAULT 0,
  last_request_date DATE DEFAULT CURRENT_DATE,
  total_requests BIGINT DEFAULT 0,
  is_blocked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.user_quotas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own quota." ON user_quotas
  FOR SELECT USING (auth.uid() = id);

-- Trigger to create quota record for new users
CREATE OR REPLACE FUNCTION public.handle_new_user_quota()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_quotas (id) VALUES (new.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created_quota
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user_quota();
